name: Deploy to heroku

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Heroku Docker Container Deploy
      uses: lucassarcanjo/heroku-deploy@2.1.17
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        formation: web
        api_key: ${{ secrets.HEROKU_API_KEY }}
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_path: ./
