name: Deploy to heroku

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    # Logging in to the registry
    - name: Docker login
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Building and pushing image to Heroku Container Registry
    - name: Build and publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME